version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Set context to the backend directory
      dockerfile: Dockerfile  # Dockerfile is in the backend folder
    container_name: backend
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend  # Mount the backend code to /app inside the container
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      DJANGO_SETTINGS_MODULE: settings
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
