version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Points to the backend directory containing the Dockerfile
    container_name: backend
    command: poetry run python manage.py runserver 0.0.0.0:8000
    working_dir: /backend
    volumes:
      - ./backend:/backend  # Mounts your backend code to /backend inside the container
    environment:
      POSTGRES_DB: field_manager_challenge  # Name of the database to create
      POSTGRES_USER: local_user             # Name of the PostgreSQL user
      POSTGRES_PASSWORD: your_password      # Password for the PostgreSQL user
      DJANGO_SETTINGS_MODULE: settings      # Django settings module
      DJANGO_DB_HOST: host.docker.internal  # Use Docker's internal host to connect to localhost
      DJANGO_DB_PORT: 5432                  # PostgreSQL default port
    ports:
      - "8000:8000"  # Exposes the Django development server on port 8000
    depends_on:
      - db           # Ensures PostgreSQL starts before Django

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: field_manager_challenge  # Database name
      POSTGRES_USER: local_user             # User created in PostgreSQL
      POSTGRES_PASSWORD: your_password      # Password for the user
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
