# Generated by Django 5.1.1 on 2024-09-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_manager', '0002_channelpartner_landowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='client',
        ),
        migrations.AddField(
            model_name='field',
            name='landowner',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='field_manager.landowner'),
            preserve_default=False,
        ),
    ]
